src/convoy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include("rest.urls")),
    path("", include("userprofiles.urls", namespace="userprofiles")),
    path("", include("post.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/post/urls.py
from django.urls import path

from .views import (PostCreate, PostDelete, PostList, PostUpdate, UserProfile,
                    get_post_from_topic, post_detail)

app_name = "post"
urlpatterns = [
    path("create/", PostCreate.as_view(), name="create"),
    path("<slug:slug>/", post_detail, name="detail"),
    path("<slug:slug>/update/", PostUpdate.as_view(), name="update"),
    path("", PostList.as_view(), name="list"),
    path("<slug:slug>/delete/", PostDelete.as_view(), name="delete"),
    path("@<username>/", UserProfile.as_view(), name="userPost"),
    path("t/<slug:slug>", get_post_from_topic, name="get_post_from_topic"),
]

src/userprofiles/urls.py
from django.urls import path

from userprofiles.views import (
    change_password,
    edit_profile,
    sign_in,
    sign_out,
    sign_up,
    user_profile,
)

app_name = "Profile"
urlpatterns = [
    path("signup/", sign_up, name="sign_up"),
    path("signin/", sign_in, name="sign_in"),
    path("signout/", sign_out, name="sign_out"),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path("profile/", user_profile, name="profile"),
    path("change_password/", change_password, name="change_password"),
]

src/userprofiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

src/userprofiles/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]


class EditProfileForm(UserChangeForm):
    password = forms.CharField(
        label="", widget=forms.TextInput(attrs={"type": "hidden"})
    )

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "password")


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        label="",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Email Address"}
        ),
    )
    first_name = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "First Name"}
        ),
    )
    last_name = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Last Name"}
        ),
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["username"].widget.attrs["placeholder"] = "User Name"
        self.fields["username"].label = ""
        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password1"].widget.attrs["placeholder"] = "Password"
        self.fields["password1"].label = ""
        self.fields["password2"].widget.attrs["class"] = "form-control"
        self.fields["password2"].widget.attrs["placeholder"] = "Confirm Password"
        self.fields["password2"].label = ""

src/userprofiles/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import redirect, render

from .forms import EditProfileForm, ProfileUpdateForm, SignUpForm


def sign_in(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, ("You have been logged in!"))
            return redirect("post:list")
        else:
            messages.success(request, ("Error logining in - please try again"))
            return redirect("Profile:sign_in")
    else:
        return render(request, "login.html", {})


def sign_up(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("You have registered"))
            return redirect("post:list")
    else:
        form = SignUpForm()
    context = {"form": form}
    return render(request, "register.html", context)


def sign_out(request):
    logout(request)
    messages.success(request, ("You have been logged out"))
    return redirect("post:list")


def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if form.is_valid() and p_form.is_valid():
            form.save()
            p_form.save()
            messages.success(request, ("You have edited you profile."))
            return redirect("Profile:edit_profile")
    else:
        form = EditProfileForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {"form": form, "p_form": p_form}
    return render(request, "edit_profile.html", context)


def user_profile(request):
    return render(request, "profile.html", {})


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, ("You have edited you password."))
            return redirect("Profile:home")
    else:
        form = PasswordChangeForm(user=request.user)

    context = {"form": form}
    return render(request, "change_password.html", context)

src/userprofiles/templates/change_password.html
{% extends 'base.html' %}
{% block content %}
<div class="nes-container with-title">
  <h2 class="title">Change Password</h2>
  <form method="POST" action="{% url 'Profile:change_password' %}">
    {% csrf_token %}
    <div>
      {{form.as_p}}
    </div>
    <input type="submit" value="Change Password" class="nes-btn is-warning">
  </form>
</div>
{% endblock %}

src/userprofiles/templates/edit_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="nes-container with-title">
  <h2 class="title">Edit Profile</h2>
    <form method="POST" action="{% url 'Profile:edit_profile' %}" enctype="multipart/form-data">
      {% csrf_token %}
      <div>
        {{form.as_p}}
        {{p_form}}
      </div>
      <input type="submit" value="Update" class="nes-btn is-warning">
    </form>
  <a href="{% url 'Profile:change_password' %}">Click Here</a><a> to change your password.</a>
</div>
{% endblock %}

src/userprofiles/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="nes-container with-title">
  <h2 class="title">Login</h2>
  <form  method="POST">
    {% csrf_token %}
    <div style="width:50px" class="nes-field is-inline">
      <input type="text" name="username" class="nes-input is-success" placeholder="Enter Username">
    </div>
    <div style="width:50px" class="nes-field is-inline">
      <input type="password" name="password" class="nes-input is-success" placeholder="Enter Password">
    </div>
    <br>
    <button type="submit" class="nes-btn is-primary">Sign In</button>
  </form>
</div>
{% endblock %}

src/userprofiles/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="nes-container with-title">
  <h1 class="title">Profile</h1>
  {% if user.is_authenticated %} 
    <img class="rounded-circle user_image" src="{{ user.profile.image.url }}"><br>
    <b>Name:</b> {{user.first_name }}</p>
    <b>Surname:</b> {{user.last_name }}</p>
    <b>Username:</b> {{ user.username }}</p>
    <b>Email:</b> {{ user.email }}</p>
  {% endif %}
  <a class="nes-btn is-success" href="{% url 'Profile:edit_profile'%}" role="button">Edit profile</a>
  {% endblock %}
</div>

src/userprofiles/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="nes-container with-title">
  <h2 class="title">Register</h2>
  <form method="POST" action="{% url 'Profile:sign_up' %}">
    {% csrf_token %}
    <div class="nes-field">
      {{form.as_p}}
    </div>
    <input type="submit" value="Register" class="nes-btn is-warning">
  </form>
</div>
{% endblock %}