src/convoy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include("rest.urls")),
    path("", include("userprofiles.urls", namespace="userprofiles")),
    path("", include("post.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/post/urls.py
from django.urls import path

from .views import (PostCreate, PostDelete, PostList, PostUpdate, UserProfile,
                    get_post_from_topic, post_detail)

app_name = "post"
urlpatterns = [
    path("create/", PostCreate.as_view(), name="create"),
    path("<slug:slug>/", post_detail, name="detail"),
    path("<slug:slug>/update/", PostUpdate.as_view(), name="update"),
    path("", PostList.as_view(), name="list"),
    path("<slug:slug>/delete/", PostDelete.as_view(), name="delete"),
    path("@<username>/", UserProfile.as_view(), name="userPost"),
    path("t/<slug:slug>", get_post_from_topic, name="get_post_from_topic"),
]

src/userprofiles/urls.py
from django.urls import path

from userprofiles.views import (
    change_password,
    edit_profile,
    sign_in,
    sign_out,
    sign_up,
    user_profile,
)

app_name = "Profile"
urlpatterns = [
    path("signup/", sign_up, name="sign_up"),
    path("signin/", sign_in, name="sign_in"),
    path("signout/", sign_out, name="sign_out"),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path("profile/", user_profile, name="profile"),
    path("change_password/", change_password, name="change_password"),
]

src/post/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from comments.models import Comment


class Topic(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(publish__lte=timezone.now())


class Post(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    publish = models.DateField(auto_now_add=True)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    @property
    def comments(self):
        return Comment.objects.filter_by_instance(self)

    @property
    def get_content_type(self):
        return ContentType.objects.get_for_model(self.__class__)


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

src/userprofiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

src/post/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "topic"]

src/userprofiles/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]


class EditProfileForm(UserChangeForm):
    password = forms.CharField(
        label="", widget=forms.TextInput(attrs={"type": "hidden"})
    )

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "password")


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        label="",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Email Address"}
        ),
    )
    first_name = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "First Name"}
        ),
    )
    last_name = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Last Name"}
        ),
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["username"].widget.attrs["placeholder"] = "User Name"
        self.fields["username"].label = ""
        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password1"].widget.attrs["placeholder"] = "Password"
        self.fields["password1"].label = ""
        self.fields["password2"].widget.attrs["class"] = "form-control"
        self.fields["password2"].widget.attrs["placeholder"] = "Confirm Password"
        self.fields["password2"].label = ""

src/post/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView

from comments.forms import CommentForm
from comments.models import Comment

from .forms import PostForm
from .models import Post, Topic


def get_post_from_topic(request, slug):
    queryset_list = Post.objects.filter(topic__slug=slug)
    paginator = Paginator(queryset_list, 8)
    page_request_var = "page"
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = dict(post_list=queryset, topic=slug, page_request_var=page_request_var)
    return render(request, "post/topic_post_list.html", context)


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    initial_data = dict(content_type=instance.get_content_type, object_id=instance.id)
    form = CommentForm(request.POST or None, initial=initial_data)

    if form.is_valid():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None

        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment = Comment.objects.create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=content_data,
            parent=parent_obj,
        )
        return redirect(new_comment.content_object.get_absolute_url())

    context = dict(
        title=instance.title,
        instance=instance,
        comments=instance.comments,
        comment_form=form,
        topic = instance.topic,
    )

    return render(request, "post/post_detail.html", context)


class PostCreate(CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


class PostUpdate(View):
    form_class = PostForm
    template_name = "post/post_form.html"

    def get(self, request, slug):
        instance = self.get_post()
        form = self.form_class(request.POST or None, instance=instance)
        context = dict(title=instance.title, instance=instance, form=form)
        return render(request, self.template_name, context)

    def post(self, request, slug):
        instance = self.get_post()
        form = self.form_class(request.POST or None, instance=instance)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect(instance.get_absolute_url())

    def get_post(self):
        return get_object_or_404(Post, slug=self.kwargs.get("slug"))


class PostList(DetailView):
    template_name = "post/post_list.html"
    model = Post

    def get(self, request):
        queryset_list = Post.objects.all()
        topic_list = Topic.objects.all()
        query = request.GET.get("q")

        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query)
                | Q(content__icontains=query)
                | Q(user__first_name__icontains=query)
                | Q(user__last_name__icontains=query)
            ).distinct()

        paginator = Paginator(queryset_list, 8)
        page_request_var = "page"
        page = request.GET.get(page_request_var)

        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)

        context = dict(
            post_list=queryset,
            topic_list=topic_list,
            page_request_var=page_request_var,
        )
        return render(request, self.template_name, context)


class PostDelete(DeleteView):
    model = Post

    def get(self, request, slug):
        instance = get_object_or_404(Post, slug=slug)
        instance.delete()
        messages.success(request, "Successfully deleted")
        return redirect("posts:list")


class UserProfile(DetailView):
    template_name = "post/user_profile.html"
    model = Post, User

    def get(self, request, username):
        user = User.objects.get(username=username)
        post_list = Post.objects.filter(user=user.pk)
        paginator = Paginator(post_list, 10)
        page = request.GET.get("page")

        try:
            Posts = paginator.page(page)
        except PageNotAnInteger:
            Posts = paginator.page(1)
        except EmptyPage:
            Posts = paginator.page(paginator.num_pages)

        if post_list == []:
            messages.add_message(
                request, messages.WARNING, "The user does not have a share!"
            )

        context = dict(Posts=Posts, user=user)
        return render(request, self.template_name, context)

src/userprofiles/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import redirect, render

from .forms import EditProfileForm, ProfileUpdateForm, SignUpForm


def sign_in(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, ("You have been logged in!"))
            return redirect("post:list")
        else:
            messages.success(request, ("Error logining in - please try again"))
            return redirect("Profile:sign_in")
    else:
        return render(request, "login.html", {})


def sign_up(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("You have registered"))
            return redirect("post:list")
    else:
        form = SignUpForm()
    context = {"form": form}
    return render(request, "register.html", context)


def sign_out(request):
    logout(request)
    messages.success(request, ("You have been logged out"))
    return redirect("post:list")


def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if form.is_valid() and p_form.is_valid():
            form.save()
            p_form.save()
            messages.success(request, ("You have edited you profile."))
            return redirect("Profile:edit_profile")
    else:
        form = EditProfileForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {"form": form, "p_form": p_form}
    return render(request, "edit_profile.html", context)


def user_profile(request):
    return render(request, "profile.html", {})


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, ("You have edited you password."))
            return redirect("Profile:home")
    else:
        form = PasswordChangeForm(user=request.user)

    context = {"form": form}
    return render(request, "change_password.html", context)

src/post/templates/post/comment_thread.html
{% extends "base.html" %}
{% block content %}
<hr>
<div>    
  <p>{{ comment.content }}</p>
  <footer>
    via <a id="user">@{{ comment.user }}</a>
    <p class="title">
    | {{ comment.timestamp|timesince }} ago 
    {% if comment.children.count > 0 %}
      {{ comment.children.count }} 
      Comment{% if comment.children.count > 1 %}s{% endif %} 
    {% endif %}
    </p>
    <a href='{{ comment.get_delete_url }}'>Delete</a>
  </footer>
  <hr/>
  <div>
    {% for child_comment in comment.children %}
    <blockquote>
      <p>{{ child_comment.content }}</p>
      <footer>
        via <a id="user"> @{{child_comment.user}}</a>
        <p class="title">| {{ child_comment.timestamp|timesince }} ago</p>
      </footer>
      <a href='{{ child_comment.get_delete_url }}'>Delete</a>
    </blockquote>
    <hr>
   {% endfor %}
    <form method="POST" action="."> 
      {% csrf_token %}
      {{ form }}
      <input type='hidden' name='parent_id' value='{{ comment.id }}'>
      <br>
      <input type='submit' value='Reply' class="nes-btn is-primary">
    </form>
  </div>
</div>
{% endblock content %}

src/post/templates/post/post_detail.html
{% extends "base.html" %}
{% block content %}

<div class="nes-container with-title">
  <h2 class="title">{{ title }}</h2>
  <img class="rounded-circle account-img post_profile" src="{{ instance.user.profile.image.url }}">
  <span>Submited by</span>
  <a href="{% url 'post:userPost' username=instance.user %}" id="user">
    @{{ instance.user }}
  </a>
  <span>{{instance.publish}}</span><br>
  <a href="{% url 'post:get_post_from_topic' slug=topic %}">
    #{{topic}}
  </a>
  {% if user.is_authenticated %}
    {% if user == instance.user %}
    <div style="float:right;">
      <a class="nes-btn is-error" href="{% url 'post:delete' slug=instance.slug%}">Delete</a>
      <a class="nes-btn is-success" href="{% url 'post:update' slug=instance.slug%}">Update</a>
    </div>
    {% endif %}
  {% endif %}
  <div>{{ instance.content}}</div>  
</div>

{% if user.is_authenticated %}
<div class="default container">
  <h2 class="title">New comment</h2>
  <form method="POST" action=".">
    {% csrf_token %}
    {{ comment_form }}
    <br>
    <input type='submit' value='Post comment' class="nes-btn is-primary">
  </form>  
</div>
{% endif %}

{% for comment in comments %}
<blockquote >
  <footer class="nes-container is-rounded">
    <p>{{ comment.content }}</p> via 
    <a id="user" href="{% url 'post:userPost' username=comment.user %}"> 
      @{{ comment.user }} 
    </a> 
    | {{ comment.timestamp|timesince }} ago |
    {% if comment.children.count > 0 %}
      {{ comment.children.count }} 
      Comment{% if comment.children.count > 1 %}s{% endif %} | 
    {% endif %} 
    </p>
    <a class='comment-reply-btn' href='#'>Reply</a> | 
    <a class='' href='{{ comment.get_absolute_url }}'>Thread</a>
  </footer>

  <div class='comment-reply'>
    {% for child_comment in comment.children %}
    <blockquote class="nes-container is-rounded">
      <p>{{ child_comment.content }}</p>
      <footer>
        via 
        <a id="user" href="{% url 'post:userPost' username=child_comment.user %}"> 
          @{{child_comment.user}}
        </a>
        | {{ child_comment.timestamp|timesince }} ago 
      </footer>
    </blockquote>
    {% endfor %}

    <form method="POST" action="."> 
      {% csrf_token %}
      {{ comment_form }}
      <input type='hidden' name='parent_id' value='{{ comment.id }}'>
      <br>
      <input type='submit' value='Reply' class="nes-btn is-success">
    </form>
  </div>
</blockquote>
{% endfor %}
{% endblock content %}

src/post/templates/post/post_form.html
{% extends "base.html" %}
{% block content %}
<div class="nes-container with-title">
	<h1 class="title">New Post</h1>
	<form method='POST' action='' enctype='multipart/form-data'>
		{% csrf_token %}
		<div class="nes-field">
		  {{ form }}
		</div>
	<input type='submit' class="nes-btn is-success" value='Create Post'/>
	</form>
</div>
{% endblock content %}

src/post/templates/post/post_list.html
{% extends "base.html" %}
{% block content %}

<div class="nes-container  with-title is-centered">
  <p class="title">Categories</p>
  {% for topic in topic_list %}
    <a class="nes-btn is-primary" href="{% url 'post:get_post_from_topic' slug=topic %}">
      {{topic}}
    </a>
    {% empty %}
    <p>No category here yet.</p>
  {% endfor %}
</div>
<br>

{% for obj in object_list %}
<div class="nes-container is-rounded">
  <a class="title_link" href="{{ obj.get_absolute_url }}">{{obj.title}}</a>
  <div>
    <span>{{obj.publish}}</span>
    <img class="rounded-circle account-img post_profile" src="{{ obj.user.profile.image.url }}">
    <a id="user" href="{% url 'post:userPost' username=obj.user %}">@{{obj.user}}</a>
  </div>
</div>
{% endfor %}

<div class="default">
  <div class="pagination">
    <span class="step-links">
      {% if object_list.has_previous %}
        <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
      </span>

      {% if object_list.has_next %}
        <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
      {% endif %}
    </span>
  </div>
</div>
{% endblock content %}

src/post/templates/post/topic_post_list.html
{% extends "base.html" %}
{% block content %}

<div class="nes-container with-title">
  <p class="title">{{topic}}</p>
  {% for post in post_list %}
  <div class="nes-container is-rounded">
    <a class="title_link" href="{{ post.get_absolute_url }}">{{post.title}}</a>
    <div>
      <span>{{post.publish}}</span>
      <img class="rounded-circle account-img post_profile" src="{{ post.user.profile.image.url }}">
      <a id="user" href="{% url 'post:userPost' username=post.user %}">@{{post.user}}</a>
    </div>
  </div>
  {% endfor %}
</div>

<div class="default">
  <div class="pagination">
    <span class="step-links">
      {% if post_list.has_previous %}
        <a href="?{{ page_request_var }}={{ post_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
      {% endif %}
      <span class="current">
        Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
      </span>
      {% if post_list.has_next %}
        <a href="?{{ page_request_var }}={{ post_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
      {% endif %}
    </span>
  </div>
</div>
{% endblock content %}

src/post/templates/post/user_profile.html
{% extends "base.html" %}
{% block content %}
<div class="default">
  <img class="rounded-circle account-img user_image" src="{{ user.profile.image.url }}">
  <h3>@{{ user.username }}</h3>
  <b>Name:</b>{{user.first_name }} |
  <b>Email:</b>{{ user.email }}
</div>

<ol>
{% for post in Posts %}
  <li class="nes-container is-rounded">
    <a class="title_link" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    <div>
      <span> {{post.publish}}</span>
      <span>| comments: {{ post.comments.count}} |</span>
      <img height="30" width="30" class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <a href="{% url 'post:userPost' username=post.user %}" id="user"> @{{ post.user }}</a>
    </div>
  </li>
{% endfor %}
</ol>

<div class="default">
  <div class="pagination">
    <span class="step-links">
      {% if Posts.has_previous %}
        <a href="?{{ page_request_var }}={{ Posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
      {% endif %}
      <span class="current">
        Page {{ Posts.number }} of {{ Posts.paginator.num_pages }}.
      </span>
      {% if Posts.has_next %}
        <a href="?{{ page_request_var }}={{ Posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
      {% endif %}
    </span>
  </div>
</div>
{% endblock content %}